- .changeset/eight-poets-pump.md
- packages/runtime/src/components/builtin/Navigation/Navigation.tsx
From MR: https://gitlab.com/makeswift/cosmos/-/merge_requests/1255
> fix: apply gutter to navigation logo

- .changeset/mean-cups-call.md
- packages/runtime/src/components/builtin/Text/Text.tsx
> fix: text selection is preserved after blur

- examples/bigcommerce/README.md
- examples/bigcommerce/components/icons.tsx
- examples/bigcommerce/components/product-cart.tsx
- examples/bigcommerce/lib/bigcommerce/types.ts
- examples/bigcommerce/lib/cart-context.tsx
- examples/bigcommerce/package.json
- examples/bigcommerce/pages/api/cart.ts
- examples/bigcommerce/pages/api/categories.ts
- examples/bigcommerce/pages/api/checkout.ts
- examples/bigcommerce/yarn.lock
This includes adding cart function and updating the readme accordingly.
> feat: add cart function to bigcommerce example

- examples/bigcommerce/lib/product-context.ts
- examples/bigcommerce/lib/types.ts
- examples/bigcommerce/pages/[[...path]].tsx
- examples/bigcommerce/pages/_app.tsx
- examples/bigcommerce/pages/makeswift.tsx
- examples/bigcommerce/pages/product/[slug].tsx
- examples/shopify/lib/product-context.ts
- examples/shopify/lib/types.ts
- examples/shopify/pages/[[...path]].tsx
- examples/shopify/pages/_app.tsx
- examples/shopify/pages/makeswift.tsx
- examples/shopify/pages/product/[slug].tsx
I tried to take a nap and it haunted me :)
> feat: update ecom example to correctly use context

- .changeset/fluffy-dingos-train.md
- packages/runtime/src/state/actions.ts
- packages/runtime/src/state/react-builder-preview.ts
https://user-images.githubusercontent.com/13066728/207834340-10a8d408-ce6c-4aa4-a870-517e7d08f4f6.mp4
> Fix content-mode overlay doesn't appear properly.

- .changeset/quick-cows-notice.md
- packages/runtime/src/components/builtin/Box/Box.tsx
- packages/runtime/src/components/builtin/Box/animations.tsx
- packages/runtime/src/components/hooks/useMediaQuery.ts
- packages/runtime/src/components/shared/BackgroundsContainer/index.tsx
- packages/runtime/src/components/shared/grid-item.tsx
There is a companion PR in www.makeswift.com repo for comparing perf with the actual site.
companion PR: https://github.com/makeswift/www.makeswift.com/pull/96
companion preview deploy: https://www-makeswift-com-git-josh-prd-910-makeswift.vercel.app/
> fix reveal animation lag (moving box animation from @framer/motion to css)

- .changeset/breezy-chefs-drop.md
- .changeset/fast-dancers-chew.md
- .changeset/happy-birds-end.md
- .changeset/metal-suits-decide.md
- .changeset/olive-shrimps-burn.md
- .changeset/red-bugs-wash.md
- .changeset/tasty-boats-enjoy.md
- .changeset/tender-onions-leave.md
- packages/runtime/package.json
- packages/runtime/src/api/react.tsx
- packages/runtime/src/components/builtin/Box/Box.tsx
- packages/runtime/src/components/builtin/Box/animations.tsx
- packages/runtime/src/components/builtin/Text/EditableText.tsx
- packages/runtime/src/components/builtin/Text/ReadOnlyText.tsx
- packages/runtime/src/components/builtin/Text/Text.tsx
- packages/runtime/src/components/builtin/register.ts
- packages/runtime/src/components/shared/BackgroundsContainer/index.tsx
- packages/runtime/src/next/document.tsx
- packages/runtime/src/runtimes/react/components/LiveProvider.tsx
- packages/runtime/src/runtimes/react/element-imperative-handle.ts
- packages/runtime/src/runtimes/react/find-dom-node.tsx
- packages/runtime/src/runtimes/react/index.tsx
- packages/runtime/src/state/actions.ts
- packages/runtime/src/state/modules/is-preview.ts
- packages/runtime/src/state/react-builder-preview.ts
- packages/runtime/src/state/react-page.ts
> Slimmer rich text, bundle size improvements, and more efficient runtime initialization

- .changeset/yellow-bananas-serve.md
- packages/runtime/src/components/builtin/Text/ReadOnlyText.tsx
> fix: lists in built-in Text component

- .changeset/lemon-queens-hang.md
- .changeset/three-queens-exist.md
- packages/runtime/src/components/page/Page.tsx
- packages/runtime/src/next/api-handler.ts
- packages/runtime/src/next/client.ts
- packages/runtime/src/next/index.tsx
- packages/runtime/src/state/modules/api-resources.ts
Will leave this in draft, since I can just build on it for snapshotting.
> Snapshot Data Format & Create Snapshot Endpoint

- .changeset/strong-moose-joke.md
- packages/runtime/src/api/introspection.ts
- packages/runtime/src/runtimes/react/index.tsx
> fix: prevent global element cycles

- packages/runtime/src/components/builtin/Form/components/Field/components/RadioButton/index.tsx
- packages/runtime/src/components/builtin/Text/EditableText/Leaf/index.ts
- packages/runtime/src/components/builtin/Text/EditableText/Leaf/leaf.tsx
- packages/runtime/src/components/builtin/Text/EditableText/Leaf/typography.tsx
- packages/runtime/src/components/builtin/Text/EditableText/editable-text.tsx
- packages/runtime/src/components/builtin/Text/EditableText/index.ts
- packages/runtime/src/components/builtin/Text/Text.tsx
- packages/runtime/src/components/utils/types.ts
- packages/runtime/src/controls/rich-text/dto-types.ts
I did look into putting this code into a plugin, but plugins are a way of editing the `Editor` and rendering is done by `Editable`.  After reading through the source/doc I don't think this is possible, but it also doesn't seem like a big loss.
> Create Leaf component for Text component

- .changeset/early-trains-wonder.md
- .changeset/famous-suits-hope.md
- .changeset/fluffy-planes-pull.md
- packages/runtime/src/components/builtin/Text/EditableText/editable-text.tsx
- packages/runtime/src/components/builtin/Text/ReadOnlyText.tsx
* Fix key prop warnings
* Add placeholder back to rich text
* Add layout polling back to rich text
> Misc rich text improvements

- .changeset/hungry-swans-invent.md
- .changeset/ninety-ladybugs-roll.md
- .changeset/olive-planes-stare.md
- .changeset/popular-eyes-peel.md
- .changeset/tame-guests-dress.md
- packages/runtime/package.json
- packages/runtime/src/api/graphql/documents/queries.ts
- packages/runtime/src/api/graphql/generated/types.ts
- packages/runtime/src/next/api-handler/handlers/manifest.ts
- packages/runtime/src/next/api-handler/handlers/proxy-preview-mode.ts
- packages/runtime/src/next/api-handler/index.ts
- packages/runtime/src/next/client.ts
- packages/runtime/src/next/index.tsx
- packages/runtime/src/next/preview-mode.tsx
- yarn.lock
Also resolves PRD-1812 and PRD-1815
> Unstable versioning endpoints for pages and swatches

- packages/runtime/src/controls/list.ts
- packages/runtime/src/controls/shape.ts
- packages/runtime/src/next/client.ts
- packages/runtime/src/prop-controllers/descriptors.ts
- packages/runtime/src/prop-controllers/introspection.ts
* Create generic introspection functions for List and Shape
* Add pageId introspection for Link Control 
josh/prd-2056
josh/prd-2058
> Update introspection for composable controls

- examples/thirdweb/components/NFTDropCard/NFTDropCard.tsx
- examples/thirdweb/lib/makeswift/register-components.tsx
- packages/runtime/CHANGELOG.md
- packages/runtime/src/next/api-handler/handlers/manifest.ts
- packages/runtime/src/runtimes/react/use-style.ts
- packages/runtime/src/slate/InlinePlugin/__test__/getValue.test.tsx
Split off from #487 to fix some small issues I noticed:
- Fixed an import issue when trying to destructure version from package.json.
- Removed a star import from React, as the expected exported function should on the default export.
- Fixed some formatting issues (yarn format)
cc. @migueloller
> chore: fix formating and import issues

- packages/runtime/src/next/api-handler/handlers/manifest.ts
This reverts commit 472fa4ccd884639c575c58cd313ef448161d9bcf.
> Revert "chore: fix import issue with package version"

- .changeset/metal-pets-call.md
- packages/runtime/src/controls/rich-text-v2/rich-text-v2.ts
- packages/runtime/src/prop-controllers/introspection.ts
- packages/runtime/src/runtimes/react/controls/rich-text-v2/rich-text-v2.tsx
related: https://gitlab.com/makeswift/cosmos/-/merge_requests/1897
> feat: add upgrade path from `RichText` to `RichTextV2`

- .changeset/fast-points-repeat.md
- .changeset/rich-horses-enjoy.md
- packages/runtime/codegen.yml
- packages/runtime/src/api/graphql/documents/fragments.ts
- packages/runtime/src/api/graphql/documents/queries.ts
- packages/runtime/src/api/graphql/generated/fragment-document-nodes.ts
- packages/runtime/src/api/graphql/generated/types.ts
- packages/runtime/src/api/react.tsx
- packages/runtime/src/next/api-handler/index.ts
- packages/runtime/src/next/client.ts
- packages/runtime/src/next/index.tsx
- packages/runtime/src/runtimes/react/index.tsx
- packages/runtime/src/state/makeswift-api-client.ts
This reverts commit b1518896023320d6d85f5f9e0d21f409290b9b51.
> Revert "feat: support localized global element"

- .changeset/fast-pianos-sort.md
- packages/runtime/package.json
- packages/runtime/src/runtimes/react/find-dom-node.tsx
- packages/runtime/src/slate/TextAlignPlugin/index.tsx
- packages/runtime/src/slate/utils/responsive.ts
- packages/runtime/src/state/modules/react-components.tsx
- yarn.lock
Resolves https://github.com/makeswift/makeswift/issues/506
> feat: upgrade TypeScript and React types

- .changeset/funny-onions-sip.md
- packages/runtime/src/next/client.ts
- packages/runtime/src/runtimes/react/index.tsx
This reverts commit ac2dfb7b22172074a855cacba55fdb735eb6e719.
> Revert "chore: remove localization unstable_ prefix"

- .changeset/healthy-lemons-grab.md
- packages/runtime/src/controls/control.ts
- packages/runtime/src/controls/list.ts
- packages/runtime/src/controls/shape.ts
- packages/runtime/src/next/api-handler/handlers/translatable-data.ts
- packages/runtime/src/next/api-handler/index.ts
- packages/runtime/src/next/client.ts
- packages/runtime/src/runtimes/react/index.tsx
- packages/runtime/src/state/react-page.ts
Resolves:
PRD-2649
PRD-2648
PRD-2647
> feat: add endpoint for translatable data

- .changeset/light-cats-prove.md
- packages/runtime/src/components/page/Page.tsx
- packages/runtime/src/next/client.ts
This reverts commit fe522b9140149014e0045c7a3c7ebe793e904856.
> Revert "feat: add hreflang tag to header"

- .github/workflows/release.yml
https://pnpm.io/using-changesets
> fix: changeset publish with pnpm

- .changeset/old-crabs-lick.md
- packages/runtime/src/controls/rich-text-v2/rich-text-v2.ts
> feat: expose `defaultValue` to `RichText` control

- .changeset/silent-flies-love.md
- packages/runtime/src/controls/__tests__/fixtures/shape.ts
- packages/runtime/src/controls/__tests__/translation.test.ts
- packages/runtime/src/controls/shape.ts
This bug deleted all data rather than merging it.
> fix: fix bug in merging translated data for the shape control

- .changeset/happy-comics-invite.md
- packages/runtime/src/next/api-handler/handlers/proxy-preview-mode.ts
https://github.com/makeswift/makeswift/assets/7907782/e52d8c84-2209-43cd-8e32-1ec9b08b9792
> Pass cookies through in preview mode

- .changeset/chilled-llamas-dream.md
- packages/runtime/src/controls/color.ts
Adds the `type` field to the color control.
Fixes PRD-4072
> feat: add type to color control

- .changeset/slimy-balloons-leave.md
- packages/runtime/src/controls/checkbox.ts
- packages/runtime/src/controls/color.ts
- packages/runtime/src/controls/control-data-type-key.ts
- packages/runtime/src/runtimes/react/controls/checkbox.ts
Adds the `type` field to the Checkbox control.
> feat: add type field to Checkbox control

- .changeset/blue-rocks-repair.md
- packages/runtime/src/controls/text-area.ts
- packages/runtime/src/runtimes/react/controls/text-area.ts
Adds the `type` and `version` field for the `TextArea` control.
> feat: add type field to TextArea control

- .changeset/config.json
- package.json
- pnpm-lock.yaml
> chore: update changsets so it properly ignores packages

- .changeset/nasty-mirrors-perform.md
- packages/runtime/src/components/hooks/useRouterLocaleSync.ts
- packages/runtime/src/components/page/Page.tsx
- packages/runtime/src/state/react-builder-preview.ts
https://github.com/makeswift/makeswift/assets/10539418/68577ce9-7dc2-47f2-adbc-7bff68457e50
> refactor: move locale switching logic out of state

- examples/bigcommerce-catalyst/app/api/categories/route.ts
- examples/bigcommerce-catalyst/app/api/quick-search/route.ts
- examples/bigcommerce-catalyst/client/queries/get-quick-search-results.ts
- examples/bigcommerce-catalyst/components/product-carousel/dummy-card.tsx
- examples/bigcommerce-catalyst/components/product-carousel/pagination.tsx
- examples/bigcommerce-catalyst/components/product-carousel/product-card.tsx
- examples/bigcommerce-catalyst/components/product-carousel/product-carousel.makeswift.ts
- examples/bigcommerce-catalyst/components/product-carousel/product-carousel.tsx
- examples/bigcommerce-catalyst/lib/makeswift/components.ts
- examples/bigcommerce-catalyst/pages/[...path].tsx
- examples/bigcommerce-catalyst/pages/_app.tsx
https://github.com/makeswift/makeswift/assets/10539418/f76906d5-8ab4-4680-8499-25370240dd33
https://github.com/makeswift/makeswift/assets/10539418/930413f2-3c58-47e2-ae5c-01cb86fae282
> feat(bigcommerce-catalyst): add ProductCarousel component

- .changeset/clean-moose-allow.md
- packages/makeswift/src/index.ts
- packages/makeswift/src/init.ts
- packages/makeswift/src/link.ts
- packages/makeswift/src/utils/get-name.ts
- packages/makeswift/src/utils/handshake.ts
https://github.com/user-attachments/assets/d15245c5-052d-4687-8c06-ca6f038b8d94
> Add link command

- packages/runtime/src/next/components/tests/controls/link-control.test.tsx
- packages/runtime/src/next/components/tests/controls/slot-control.test.tsx
- packages/runtime/src/runtimes/react/components/ElementData.tsx
Will resubmit as a separate PR.
> runtime: take `canAcceptRef` out of the imminent release

- packages/runtime/src/utils/__tests__/partition.test.ts
- packages/runtime/src/utils/partition.ts
Pure addition, prep for https://github.com/makeswift/makeswift/pull/814.
> feat: `partition`/`partitionRecord` utils

- .changeset/ten-rules-march.md
- packages/runtime/src/next/components/tests/__snapshots__/global-element-rendering.test.tsx.snap
- packages/runtime/src/next/components/tests/controls/page-control-prop-rendering.tsx
- packages/runtime/src/next/components/tests/global-element-rendering.test.tsx
- packages/runtime/src/utils/tests/element-data-test-test.ts
> test(runtime): add global elements rendering tests

- .changeset/lemon-pugs-battle.md
- packages/runtime/src/runtimes/react/react-runtime.ts
> fix: validate component type at runtime

- .changeset/thick-onions-remain.md
- packages/runtime/package.json
- packages/runtime/src/runtimes/react/components/LiveProvider.tsx
- packages/runtime/src/runtimes/react/runtime-core.ts
- packages/runtime/src/state/makeswift-api-client.ts
- packages/runtime/src/state/react-builder-preview.ts
- packages/runtime/src/state/react-page.test.tsx
- packages/runtime/src/state/react-page.ts
- packages/runtime/src/utils/__tests__/__snapshots__/serializeState.test.ts.snap
- packages/runtime/src/utils/__tests__/serializeState.test.ts
- packages/runtime/src/utils/serializeState.ts
- pnpm-lock.yaml
Logging to Redux Devtools is enabled in development only.
https://github.com/user-attachments/assets/a56f09fe-2e8c-485d-b049-14013453dca0
> debug(runtime): configure Redux Devtools logging for all `runtime` stores

- .changeset/shy-jeans-join.md
- packages/runtime/src/components/shared/Link/index.tsx
Dev: 
https://github.com/user-attachments/assets/c3721867-c1b8-472a-9fc8-f39ae545e558
Prod:
https://github.com/user-attachments/assets/9b02179b-d4d7-4b66-b446-34ff1420bf99
Dev:
https://github.com/user-attachments/assets/67cac23c-a773-43b7-82ca-f74f412a4562
Prod:
https://github.com/user-attachments/assets/09aa264c-13b6-4d5a-aad9-0a94e044766e
> fix(runtime): Pages Router links from localized to base pages don't work

- .changeset/honest-moose-film.md
- packages/runtime/src/jest-setup.ts
- packages/runtime/src/next/client.ts
- packages/runtime/src/next/components/MakeswiftComponent.tsx
- packages/runtime/src/next/components/tests/makeswift-component-rendering.test.tsx
- packages/runtime/src/runtimes/react/components/Document.tsx
- packages/runtime/src/runtimes/react/components/DocumentRoot.tsx
- packages/runtime/src/runtimes/react/components/Element.tsx
- packages/runtime/src/runtimes/react/components/ElementRegistration.tsx
- packages/runtime/src/state/modules/read-only-documents.ts
> feat: add fallback prop to embedded component

- .changeset/twenty-seas-suffer.md
Add forgotten changeset for 6f883458c51c086c3ec2e6fe851bdaf8efd911e3
> chore: release runtime

- .changeset/fifty-bikes-walk.md
- packages/runtime/src/controls/rich-text-v2/rich-text-v2.ts
Cherry-picking from https://github.com/makeswift/makeswift/pull/868
> fix: "attempted import" errors on registering component in server-side code

- .changeset/nine-spoons-know.md
- packages/runtime/src/runtimes/react/controls/control.tsx
https://github.com/user-attachments/assets/5e9245ed-7d0a-4e2e-833d-e7bb7591407e
> fix: do not crash on incompatible prop data

- .changeset/tough-candles-travel.md
- apps/nextjs-app-router/src/app/[lang]/layout.tsx
- apps/nextjs-app-router/src/app/api/makeswift/[...makeswift]/route.ts
- apps/nextjs-app-router/src/components/font-control-demo/font-control-demo.makeswift.ts
- apps/nextjs-app-router/src/components/font-control-demo/font-control-demo.tsx
- apps/nextjs-app-router/src/makeswift/components.ts
- apps/nextjs-pages-router/src/components/font-control-demo/font-control-demo.makeswift.ts
- apps/nextjs-pages-router/src/components/font-control-demo/font-control-demo.tsx
- apps/nextjs-pages-router/src/makeswift/components.ts
- apps/nextjs-pages-router/src/pages/_app.tsx
- apps/nextjs-pages-router/src/pages/api/makeswift/[...makeswift].ts
- packages/controls/src/controls/definition.ts
- packages/controls/src/controls/font/__snapshots__/font.test.ts.snap
- packages/controls/src/controls/font/font.test.ts
- packages/controls/src/controls/font/font.test.types.ts
- packages/controls/src/controls/font/font.ts
- packages/controls/src/controls/font/index.ts
- packages/controls/src/controls/index.ts
- packages/runtime/src/builder/serialization/control-serialization.ts
- packages/runtime/src/controls/index.ts
- packages/runtime/src/core/index.ts
- packages/runtime/src/next/components/tests/controls/__snapshots__/font-control.test.tsx.snap
- packages/runtime/src/next/components/tests/controls/font-control.test.tsx
- packages/runtime/src/runtimes/react/controls.tsx
- packages/runtime/src/runtimes/react/controls/control.tsx
> Feat: font control

- packages/runtime/src/next/client.ts
- packages/runtime/src/next/components/MakeswiftComponent.tsx
- packages/runtime/src/next/components/tests/makeswift-component-rendering.test.tsx
Before:
https://github.com/user-attachments/assets/148a207b-278d-45ee-84a0-a3d85e5397d5
After:
https://github.com/user-attachments/assets/f966be87-5e63-4949-93e5-2de3c4c8983d
> fix: use deterministic element tree document keys

- packages/controls/src/controls/shape/v2/shape-v2.ts
... plus related cleanup.
Prep for fixing a host of Shape v2 issues in the builder.
> refactor(shape v2): introduce `itemsData`, `itemDataPath` methods

- .github/workflows/preview-deployment-playwright-tests.yml
Cherry-pick https://github.com/makeswift/makeswift/pull/908 from `main`.
> fix(actions): Use ubuntu-22.04

- .changeset/fresh-baboons-poke.md
- packages/runtime/package.json
- pnpm-lock.yaml
Upgraded to the latest version of `react-player` to resolve constant flow of console warnings.
> fix: console warnings from the `Video` component

- packages/runtime/src/next/api-handler/handlers/proxy-draft-mode.test.ts
> chore: formatting fixes

- security.md
Adding this at the request of Francis, from BC security
> Add `security.md`

- .changeset/khaki-bags-lead.md
- packages/runtime/src/next/components/tests/controls/rich-text-v2-control/__snapshots__/server.test.tsx.snap
- packages/runtime/src/next/components/tests/controls/style-control/__snapshots__/client.test.tsx.snap
- packages/runtime/src/next/components/tests/controls/style-control/__snapshots__/server.test.tsx.snap
- packages/runtime/src/next/root-style-registry.tsx
Change the default Emotion cache key from `css` to `mswft` to reduce the risk of conflicts with the host's code.
Resolves #964
> fix: change the default Emotion cache key

- .changeset/shy-candles-float.md
- packages/runtime/src/runtimes/react/hooks/use-register-document.ts
After:
https://github.com/user-attachments/assets/10d6797e-b224-457c-8d2b-69c861db7beb
> Create/register prop controllers for documents added after (host <--> builder) connection established

- .changeset/new-maps-kick.md
- packages/runtime/src/next/client.ts
- packages/runtime/src/next/tests/client.error-handling.test.ts
- packages/runtime/src/next/tests/client.get-component-snapshot.test.ts
- packages/runtime/src/next/tests/client.get-page-snapshot.test.ts
- packages/runtime/src/next/tests/client.get-pages.test.ts
- packages/runtime/src/next/tests/client.get-resources.test.ts
> chore: improve error messages/logging in Makeswift client

- .changeset/heavy-rice-complain.md
- packages/runtime/package.json
- packages/runtime/src/builder/index.ts
- packages/runtime/src/builder/unstructured-introspection/__fixtures__/element-containing-resources.ts
- packages/runtime/src/builder/unstructured-introspection/__fixtures__/index.ts
- packages/runtime/src/builder/unstructured-introspection/__snapshots__/unstructured-introspection.test.ts.snap
- packages/runtime/src/builder/unstructured-introspection/index.ts
- packages/runtime/src/builder/unstructured-introspection/unstructured-introspection.test.ts
- packages/runtime/src/builder/unstructured-introspection/unstructured-introspection.ts
- pnpm-lock.yaml
Companion PR: https://github.com/makeswift/cosmos/pull/1266
> Add helper for introspecting without controls

- packages/makeswift-next-plugin/index.js
Review with the "Hide whitespace" toggle on.
> chore: prettier reformat, no other changes

- .changeset/silent-boxes-peel.md
Follow-up to https://github.com/makeswift/makeswift/pull/1012.
> chore: `next-plugin` version bump

- pnpm-lock.yaml
Following up on the Contentful example's rework.
> chore: update `pnpm-lock.yaml`

- packages/runtime/src/components/hooks/useMediaQuery.ts
- packages/runtime/src/runtimes/react/hooks/makeswift-api.ts
- packages/runtime/src/runtimes/react/hooks/use-selector.ts
> chore: don't use `use-sync-external-store/shim`

- .changeset/new-ligers-rhyme.md
- packages/express-react/.prettierrc
- packages/express-react/README.md
- packages/express-react/jest.config.json
- packages/express-react/package.json
- packages/express-react/server/package.json
- packages/express-react/src/client.ts
- packages/express-react/src/index.ts
- packages/express-react/src/root-style-registry.tsx
- packages/express-react/src/server/api-handler.ts
- packages/express-react/src/server/index.ts
- packages/express-react/src/server/preview.ts
- packages/express-react/src/server/render.tsx
- packages/express-react/src/server/site-version.tsx
- packages/express-react/tsconfig.json
- packages/express-react/tsup.config.ts
- pnpm-lock.yaml
`express-react` package, initial alpha release
> feat: alpha `express-react` package

- packages/express-react/package.json
Following up https://github.com/makeswift/makeswift/pull/1129
> chore: set `express-react`version to `0.0.0`, to be bumped by changeset

- .github/workflows/ci.yml
- .github/workflows/snapshot-release.yml
- Prevents comment thrashing between snapshot releases and bundle analysis
- Adds additional text to analysis reports
> Augment CI bundle analysis
