makeswift/makeswift

.changeset/seven-ghosts-taste.md, packages/runtime/vite.config.ts
This would fix one issue where social icons aren't sized correctly,
because svgo is removing the viewBox.
=> fix: disable svgo plugin on svgr

.changeset/yellow-wombats-peel.md, packages/runtime/src/runtimes/react/index.tsx
Before, when you put two nested global components, the overlay is shown
on the wrong element.
This is happening because a nested global element have the same key,
and we're registering all elements.
This commit fix it by disabling element registration, when it's inside
an unfocused element reference. We know whether element reference
is focused or not, by checking whether the elementReferenceDocument
is null.
=> fix: disable element registration inside unfocused element reference

.changeset/spotty-trees-drive.md, packages/runtime/src/components/builtin/Button/Button.tsx
This fix a bug in Form component where we extend
the Button, but the style isn't applied
because we didn't pass the className
=> fix: pass className prop on Button

.changeset/hip-wolves-talk.md, packages/runtime/codegen.yml, packages/runtime/package.json, packages/runtime/src/api/constants.ts, packages/runtime/src/api/fragments.graphql, packages/runtime/src/api/generated/graphql.ts, packages/runtime/src/api/react.tsx, packages/runtime/src/api/types.ts, packages/runtime/src/components/page/Page.tsx, packages/runtime/src/next.tsx, yarn.lock
Problems:
1. Snippets aren't updating immediately when added, removed, or edited.
This is because we got the snippets value from getServerSideProps, which
doesn't get updated when there's any change in apollo cache.
This MR use the snippets value from apollo cache when it's in preview.
2. Snippet set to "Live page" is still showing in the builder.
We forgot to pass the preview props on the Page component.
I need to add the `typescript` to the codegen because we need to access the `SnippetLocation` enum, which isn't generated if we're just using the `typescript-operations`. Let me know if there's any config to add the `SnippetLocation` enum without generating the whole thing.
=> fix: snippets issues

.changeset/silver-news-pull.md, packages/runtime/src/state/actions.ts, packages/runtime/src/state/react-builder-preview.ts
This will fix scrolling doesn't work in content mode
when hovering over a text block
=> fix: send onwheel event to builder

.changeset/dirty-lions-leave.md, packages/runtime/src/api/react.tsx, packages/runtime/src/components/builtin/Image/Image.tsx, packages/runtime/src/components/shared/BackgroundsContainer/components/Backgrounds/index.tsx, packages/runtime/src/next.tsx
We were calling Apollo's `getDataFromTree` to fill the cache. The React
tree that was being used didn't include Next.js context which caused
issue with Next.js features like `next/image` and its router.
Specifically, Next.js uses React context to provide valid domains for
`next/image` and its router values but we weren't providing these
context values when rendering components in `getStaticProps` and
`getServerSideProps` using `getDataFromTree`. We now work around this by
calling `getDataFromTree` in the `Document` component where we can
render Next.js' `AppTree`, which includes its context.
=> fix: SSR for `next/image` and Next.js router

.changeset/happy-swans-punch.md, packages/runtime/src/components/builtin/Image/Image.tsx
This is creating issue in live pages, where link is not working
in Image, because we're not forwarding the prop from ImageContainer
to Link component.
=> fix: forward link prop in ImageContainer

.changeset/soft-ears-love.md, packages/runtime/src/runtimes/react/index.tsx
The `useSuppressRefWarning` hook would patch `console.error` for each
element mounted, this would result in a stack overflow if the method was
patched enough times. We now ensure we only patch the method only once.
=> fix: stack overflow with console.error

.changeset/sour-clocks-sit.md, packages/runtime/src/components/shared/Link/index.tsx
Passing an empty string causes Next.js to pick the current page, which
can result in issues if the current page is a dynamic route, since the
path doesn't exist. i.e., `/[[...path]]`.
=> fix: don't allow empty string for next/link href

.changeset/fast-hotels-suffer.md, packages/runtime/src/runtimes/react/index.tsx
When we started using `useImperativeHandle` in the `ElementData`
component, the forwarded ref shouldn't have been used anymore except as
the first argument of `useImperativeHandle`.
=> fix: ref for component not found fallback

.changeset/silent-boxes-fry.md, packages/runtime/src/components/shared/Link/index.tsx
Using next/link with relative paths in dynamic routes resulted in
Next.js pre-pending the route in the path and messing up the URL.
=> fix: avoid using next/link for relative paths

examples/bigcommerce/next.config.js, examples/bigcommerce/package.json, examples/bigcommerce/yarn.lock, examples/shopify/next.config.js, examples/shopify/package.json, examples/shopify/yarn.lock
Running into issues with cached results in 12.2 of next so I am setting a static version for now. Additionally, removing the `swcMinify` because with the downgrade it was causing a clientside minification error like this guy: 
Not sure if 12.1 even supports swcMinify so that is why I am just removing it.
=> Set static version of Next.js for ecommerce example

.changeset/neat-ligers-complain.md, packages/runtime/src/components/builtin/Carousel/Carousel.tsx, packages/runtime/src/components/builtin/Countdown/Countdown.tsx, packages/runtime/src/components/builtin/Video/Video.tsx
It seems that these were lost when we migrated to emotion.
=> fix: default width for Carousel, Countdown, Video

examples/bigcommerce/components/product-details.tsx, examples/bigcommerce/lib/bigcommerce/api.ts, examples/bigcommerce/pages/[[...path]].tsx, examples/bigcommerce/pages/makeswift.tsx, examples/shopify/components/product-details.tsx, examples/shopify/lib/shopify/api.ts, examples/shopify/lib/shopify/index.ts, examples/shopify/lib/shopify/types.ts, examples/shopify/pages/[[...path]].tsx, examples/shopify/pages/makeswift.tsx
Currently this line is causing `/product/foobar` to 500 instead of 404.
=> fix: remove throw that is preventing product 404

.changeset/rotten-peas-beg.md, packages/makeswift-next-plugin/index.js
For some reason, when deployed on Vercel, rewrites weren't matching the `/` path. It seems that Vercel's infratructure uses different logic to match rewrites than Next.js.
=> fix: Preview Mode rewrites

packages/makeswift/package.json, packages/makeswift/src/integrate-next-app.ts, yarn.lock
This leaves the filesystem clean if they decide to cancel on the site selection page.
There is a bit of a race condition that occurs now, as shown in this video (use sound)
https://user-images.githubusercontent.com/7907782/194921856-e85acd5c-4a86-4c6a-84cc-21119b05022c.mov
=> Integrate Next App in a staging environment

packages/makeswift-next-plugin/index.js
We're using a query instead of a header because we load the font using `new FontFace().load()` that doesn't support adding a custom header.
=> fix: CORS issue when loading local font

.changeset/polite-chairs-approve.md, packages/makeswift-next-plugin/index.js
Holy `js` didn't catch this.
The error:
With this hotfix, I tested with no `headers`, CORS is working. Tested with `headers`, other `headers` are still applied.
=> hotfix: next plugin errors when `headers` is null.

.changeset/grumpy-suits-retire.md, packages/runtime/src/components/builtin/Form/components/Field/index.tsx
https://user-images.githubusercontent.com/13066728/204128016-2b3971ae-557e-415e-b646-f9f7eb075efc.mp4
The malformed form (no pun intended) was causing the `CreateTableRecord` mutation to send the wrong data for the field containing a dot.
I tested the fix and it's properly added to the database.
=> fix: column with a dot not recording data

.changeset/unlucky-carrots-remain.md, packages/runtime/src/components/builtin/Form/components/Field/index.tsx
Previously, we had an issue where a dot `.` in a table column name was causing the data for that column to not be recorded. This was caused by [Formik nested object behavior](https://formik.org/docs/guides/arrays#avoid-nesting). We fixed that by wrapping the value to be `['${tableColumn.name}']`.
This causes a new problem where an apostrophe `'` in a table column name was causing the data for that column to not be recorded again. This is happening because Formik is wrapping the name inside a quote`'`. For example, if we have a column name of `hello'world`, formik will change it to `'hello'world`.
We fix this by escaping the `'` character, before passing it to Formik. We also need to escape `[` and `]` because it's used by [Lodash set array](https://lodash.com/docs/4.17.15#set) that Formik …
=> fix: [ ] ' in table column causing data to not be recorded.

.changeset/thin-mirrors-behave.md, packages/runtime/src/next/preview-mode.tsx
When sending a request to a separate origin, we need to make sure we don't include the Preview Mode header because the
Access-Control-Allow-Headers response header might prevent the request. Because we're patching `fetch` we need to make sure normal requests don't fail.
=> fix: CORS issues with headers

.changeset/shiny-swans-promise.md, packages/runtime/src/runtimes/react/index.tsx
This breaks up the work being done when React is hydrating the element tree, greatly reducing Total Blocking Time by yielding to the main thread while hydrating.
=> feat: wrap element data in Suspense boundary

.changeset/tender-hairs-argue.md, packages/runtime/src/css/border-radius.ts, packages/runtime/src/css/border.ts, packages/runtime/src/css/margin.ts, packages/runtime/src/css/padding.ts
We did a falsy check instead of checking for `undefined` or `null` explicitly, causing `0` values to be ignored for margin, padding, border, and border-radius, due to `0` being falsy.
=> fix: falsy check on Style control utils

.changeset/proud-otters-hammer.md, .changeset/twelve-knives-count.md, packages/runtime/src/api/react.tsx, packages/runtime/src/components/builtin/Video/Video.tsx, packages/runtime/src/next/index.tsx, packages/runtime/src/state/actions.ts, packages/runtime/src/state/makeswift-api-client.ts, packages/runtime/src/state/modules/api-resources.ts
See https://github.com/cookpete/react-player/issues/1428 for more information about why ReactPlayer shouldn't be rendered on the server. Ideally this is something that would be handled internally by the ReactPlayer component, but alas, we must take care of it ourselves. We should replace ReactPlayer with a more robust solution for our built-in Video component.
---
Resolves PRD-948
=> Fix SSR hydration issue with ReactPlayer and API resource cache issues

.changeset/modern-drinks-yawn.md, packages/runtime/src/components/builtin/index.ts, packages/runtime/src/index.ts
We need MakeswiftComponentType on the builder, but we don't want to import it from `@makeswift/runtime/components` because we only need the constant, and not other things that's included in the components entrypoint.
=> chore: move `MakeswiftComponentType` to main.js

.changeset/quick-carpets-fly.md, packages/runtime/src/next/index.tsx
Because we're using a useState for snippets in Page, when we change the document/page, the Page component is still preserving the old state, which was for the old document/ page.
We add key to reset the snippets state, when the document/page is changed.
https://beta.reactjs.org/learn/preserving-and-resetting-state
https://user-images.githubusercontent.com/13066728/214278992-4affaa87-7b09-45f5-a66f-2c129d3f329b.mp4
=> fix: snippets don't run on client-side navigation

.changeset/flat-squids-search.md, packages/runtime/src/components/builtin/Form/components/Field/components/RadioButton/index.tsx
It was because we were not passing the children prop on the Container
=> fix: input not rendered on a single select column

examples/basic-typescript/package.json, examples/basic-typescript/yarn.lock, examples/bigcommerce/package.json, examples/bigcommerce/yarn.lock, examples/react-countup/package.json, examples/react-countup/yarn.lock, examples/shopify/package.json, examples/shopify/yarn.lock, examples/thirdweb/package.json, examples/thirdweb/yarn.lock
This is to fix the next/dynamic preloading issue.
=> chore: upgrade next to v13.1.7-canary.5

packages/makeswift/package.json, yarn.lock
I can't find the change logs specific to `create-next-app`. This is the [commit history](https://github.com/vercel/next.js/commits/canary/packages/create-next-app) if we want to see all the changes.
I tested both for creating a fresh init and integrating from a create-next-app. It seems that both are still working. Not sure if there's anything specific that I need to test
=> chore: update CLI create-next-app to 13.1.6

.changeset/nervous-eagles-film.md, packages/runtime/src/components/builtin/Text/ReadOnlyText.tsx
See https://github.com/ConvertKit/slate-plugins/blob/master/packages/slate-lists/src/create-render-block.js for how `@convertkit/slate-lists` handles it
=> fix: rich text list block inconsistencies

.changeset/twenty-mirrors-laugh.md, packages/makeswift-next-plugin/index.js
On `@makeswift/runtime` version `0.7.0` we had an update that uses the `remotePatterns` feature, but it's only available from Next.js version `12.3.0` or higher.
So we can either drop support for `12.2.x` or add the experimental `remotePatterns` when they are using version `12.2.x`.
=> Fix images not loading when using Next.js version 12.2.x

.changeset/few-trains-stare.md, packages/runtime/src/components/builtin/Box/Box.tsx, packages/runtime/src/components/builtin/Form/Form.tsx, packages/runtime/src/components/builtin/Text/EditableText.tsx, packages/runtime/src/index.ts, packages/runtime/src/next/api-handler.ts, packages/runtime/src/runtimes/react/element-imperative-handle.ts, packages/runtime/src/state/actions.ts, packages/runtime/src/state/modules/element-imperative-handles.ts, packages/runtime/src/state/modules/pointer.ts, packages/runtime/src/state/react-builder-preview.ts
- Use builder pointer information and DOM APIs to reliably determine the active element. This guarantees that the Makeswift builder can properly select elements even if their CSS box models overlap (e.g., absolute and fixed position elements).
Resolves PRD-1294 and PRD-1293
=> New element selection algorithm based on Document.elementFromPoint

.changeset/happy-spoons-reply.md, packages/runtime/src/state/modules/read-only-documents.ts, packages/runtime/src/state/react-builder-preview.ts, packages/runtime/src/state/react-page.ts
Global element root element handles were conflicting with the handle of the element reference itself. This was resulting in element from point always returning the element handle for the element reference, even when focused on a global element.
=> fix: element from point for global elements

.changeset/three-jeans-learn.md, packages/runtime/src/state/react-builder-preview.ts
We don't want to handle esc key bind anymore because it could interfere with users code.
=> fix: remove esc key bind during interaction mode

.changeset/happy-turkeys-itch.md, packages/runtime/package.json, packages/runtime/src/controls/rich-text/dto-types.ts, packages/runtime/vite.config.ts
I'm moving the slate plugins into leo, but I don't want to forget these changes that were required to access the plugin from `@makeswift/runtime/slate`
=> chore: finish setup for slate plugins

.changeset/itchy-waves-pay.md, packages/runtime/src/state/react-builder-preview.ts
By pushing a relative path, Next.js client-side navigation was broken. We now ensure paths start with a "/".
=> fix: path normalization

.github/workflows/ci.yml, package.json, packages/runtime/package.json, turbo.json, yarn.lock
Adds `madge` so we can check and monitory for circular dependency issues. Currently, the task should be **non-blocking** but providing it in CI so we can keep track of it.
ping @migueloller
=> chore: add madge to check for circular deps

.changeset/nine-windows-join.md, packages/runtime/src/components/builtin/Carousel/register.ts, packages/runtime/src/components/builtin/Countdown/register.ts, packages/runtime/src/components/builtin/Divider/register.ts, packages/runtime/src/components/builtin/Embed/register.ts, packages/runtime/src/components/builtin/Form/register.ts, packages/runtime/src/components/builtin/Navigation/register.ts, packages/runtime/src/components/builtin/SocialLinks/register.ts, packages/runtime/src/components/builtin/Video/register.ts, packages/runtime/src/index.ts, packages/runtime/src/runtimes/react/index.tsx, packages/runtime/src/state/modules/components-meta.ts, packages/runtime/src/state/react-page.test.tsx
This breaking change uses an ComponentIcon const instead of a string literal union in the ComponentMeta. With this change, icons are no longer specified with a size attached. All component registrations have been updated to reflect this update.
=> fix: change runtime to use ComponentIcon const

.changeset/silent-tomatoes-cheat.md, packages/runtime/src/state/modules/components-meta.ts
Introduces 13 new icons to the Makeswift runtime
=> feat: add new icon support to runtime

packages/runtime/src/api/react.tsx, packages/runtime/src/components/page/Page.tsx, packages/runtime/src/controls/rich-text/translation.ts, packages/runtime/src/controls/shape.ts, packages/runtime/src/next/client.ts, packages/runtime/src/next/document.tsx, packages/runtime/src/prop-controllers/descriptors.ts, packages/runtime/src/runtimes/react/index.tsx
Removes the circular dependencies for the `MakeswiftApiHandler` route and also starts to add `use client` directives where needed.
_**Note: The modules using `use client` still won't work since rollup strips these directives on build.**_
We now got it to a point where we can start to build a new module for supporting NextJS route handlers. We need to determine what the public API will need to look like before we can continue down that path.
Got the app directory working up to the point of needing a new interface for route handlers:
=> chore: remove circular deps for MakeswiftApiHandler

.changeset/funny-onions-sip.md, packages/runtime/src/next/client.ts, packages/runtime/src/runtimes/react/index.tsx
Example usage:
```ts
export const runtime = new ReactRuntime({
i18n: {
locales: ["es", "en-US", "es-SE", "id-ID", "ba-LU", "aa-AL"],
defaultLocale: "en-US",
},
});
```
on `getPageSnapshot`:
```ts
const snapshot = await makeswift.getPageSnapshot(path, {
preview: ctx.preview,
locale: ctx.locale,
});
```
=> chore: remove localization unstable_ prefix

packages/runtime/src/api/react.tsx, packages/runtime/src/next/client.ts
This is to distinguish whether we've tried to fetch the resource or not.
=> fix: make localized resource map nullable

.changeset/light-drinks-heal.md, .changeset/spicy-trainers-accept.md, packages/runtime/src/api/graphql/documents/queries.ts, packages/runtime/src/api/graphql/generated/types.ts, packages/runtime/src/api/react.tsx, packages/runtime/src/next/api-handler/index.ts, packages/runtime/src/next/client.ts, packages/runtime/src/state/makeswift-api-client.ts
This PR focuses on getting the localized pathname.
For path-based localization, we don't have to worry about the `/es` prefix, because it's already handled by NextLink. For example, if I'm on `localhost/es/localization-1`, and I have a Button component set to Localization 2 page, then the link would be `localhost/es/localization-2`. But if I'm on `foo.es/localization-1`, then the link would be `foo.es/localization-2`.
There are several decisions that we need to make when implementing this:
1. Should we modify the existing `pagePathnamesById` query, or should we make a new query?
2. Should we reuse the existing `PagePathnameSlice` fragment, or should we make a new fragment?
For localized global elements, we have a new fragment and we have a new query because we thought that we would need …
=> feat: use localized pathname on LinkControl

examples/basic-typescript/README.md
Changes project and repo name to `makeswift-nextjs-starter`.
=> chore: change basic-typescript deploy button names

examples/basic-typescript/package.json, examples/basic-typescript/pnpm-lock.yaml, examples/bigcommerce/package.json, examples/bigcommerce/yarn.lock, examples/shopify/package.json, examples/shopify/yarn.lock, examples/thirdweb/package.json, examples/thirdweb/yarn.lock
Resolve mismatch between builder runtime version and example versions, which was causing incompatibility issues with builder sites that were created with images.
=> fix: update example runtimes

.changeset/afraid-ears-smell.md, .changeset/bright-tools-rhyme.md, .changeset/twenty-points-jump.md, packages/runtime/src/components/builtin/SocialLinks/SocialLinks.tsx, packages/runtime/src/components/builtin/SocialLinks/options.tsx, packages/runtime/src/prop-controllers/descriptors.ts
The TypeScript types weren't reflective of the supported options for the SocialLink component and there was a typo where the type for the X social link was in uppercase instead of lowercase.
=> fix: SocialLinks options

.changeset/cuddly-eels-sell.md, .changeset/strong-bananas-shake.md, packages/runtime/src/controls/checkbox.ts, packages/runtime/src/controls/color.ts, packages/runtime/src/controls/number.ts, packages/runtime/src/runtimes/react/controls/number.ts
Adds the `type` and `version` field for the `Number` control.
I also "refactored" the previous `Checkbox` and `Color` control to use the locally scope key variable.
=> feat: add type field to Number control

.changeset/sixty-islands-exist.md, packages/runtime/src/next/api-handler/handlers/manifest.ts, packages/runtime/src/next/api-handler/index.ts, packages/runtime/src/next/client.ts, packages/runtime/src/next/index.tsx
Thoughts about this MR:
1. Should we make make `siteVersion` parameter optional on public methods `getPage()` and `getPages()`?
2. Should we make the `siteVersion` parameter an object parameter like this?
```ts
async getGlobalElement(id, { siteVersion })
```
3. I think for "internal methods" like `getSwatch`, we need to make the `siteVersion` required, because otherwise we will forget to pass the `siteVersion` when we use it internally. But for external API, I'm making those optional for now, not sure which one is better here.
4. On that note, it's so weird to have a Makeswift client, but we expose our "internal methods" like `getSwatch`. In the future, it might be better to separate Makeswift client that users will use, and a Makeswift client that we use internally.
=> feat: enable versioning by default

.changeset/config.json
Despite the apps we have being `private: true` they are included in our since they depend on @makeswift/runtime and it is being update. So I am manually ignoring them.
=> chore: ignore `/apps` directory in changeset

.changeset/old-meals-bathe.md, packages/runtime/src/index.ts, packages/runtime/src/next/api-handler/handlers/manifest.ts, packages/runtime/src/state/actions.ts, packages/runtime/src/state/react-builder-preview.ts
Removes client-side routing from the state as it's being tightly coupled to Next.js routing. We want to implement client side routing, but need to think of a better way to integrate it into state.
=> feat: remove client-side-routing code

.changeset/few-scissors-sleep.md, packages/runtime/src/components/hooks/usePageSnippets.ts, packages/runtime/src/components/page/Page.tsx, packages/runtime/src/components/page/PageHead.tsx, packages/runtime/src/next/components/head-tags.tsx, packages/runtime/src/next/hooks/use-is-pages-router.ts
Introduces `PageHead` component, which renders title/meta/link data for pages in both app and pages router. Currently only supports snippet rendering for pages router. For pages router, uses Next/Head to render content directly in document head. For app router, uses React canary extensions to DOM elements, which are automatically rendered in the `head` tag.
=> feat: metadata/fonts/title in head for app router

.changeset/red-mirrors-agree.md, packages/runtime/src/slate/TypographyPlugin/__tests__/normalization.test.tsx, packages/runtime/src/slate/TypographyPlugin/normalizeTypographyUp.ts, turbo.json
Prior to translation we normalize all our `typography` richtext data to the highest ancestor for the simplest possible markup. To do this we go through children determining what parts of `typography` they share. Any `typography` data that is shared is pushed up the tree, while unique `typography` data is left behind.
We do an `and` and an `xor` to determine what is shared and unique. In the case of detached `typography` the logic was incorrect. It was pushing data up the tree wtihout removing it from the original location. This left our normalization in a infinite loop.
My hunch is I added this special case as an optimization, so I am just removing it.
=> fix: fix bug in translation of detached typography

.github/workflows/release.yml
The Vercel deployments for the changeset release GitHub Action PR were failing because it was running `pnpm install --frozen-lockfile` but there were changes in `package.json` that weren't reflected in the lock file. The additional steps now update the lock file with any changes.
=> ci: commit lock file changes during release

.changeset/good-bulldogs-beg.md, .changeset/sweet-monkeys-reply.md, packages/runtime/src/api/resource-types.ts, packages/runtime/src/components/shared/Link/index.tsx, packages/runtime/src/next/api-handler/handlers/proxy-draft-mode.ts, packages/runtime/src/next/client.ts, packages/runtime/src/runtimes/react/controls/link.ts, packages/runtime/src/runtimes/react/hooks/makeswift-api.ts
Hydrates Link control and Button component with localized page path, if applicable. Supports both App Router and Pages Router. Also resolves an existing bug where App Router API handler requests are unauthorized due to not reading the secret from the rewritten request header.
Demo: 
https://github.com/makeswift/makeswift/assets/8345645/b505cdb7-6f20-43a5-b93a-993664a89ec8
https://github.com/makeswift/makeswift/assets/8345645/15f0ee3c-dc44-4ae2-a51b-422e3257c104
=> fix: hydrate App Router link with locales

.changeset/yellow-turtles-check.md, packages/runtime/src/next/components/page.tsx
Wraps the `RuntimeProvider` component in a `Suspense` boundary as it uses `React.lazy`. Not wrapping the component would cause a hydration mismatch between the server and client.
=> fix(runtime): wraps the RuntimeProvider component in suspense boundary

.changeset/gentle-planets-doubt.md, packages/runtime/src/next/components/page.tsx
Once documentation is public, I can update this message with a link to it.
=> feat: throw runtime error when passing `runtime` to `Page`

.changeset/hip-chicken-occur.md, packages/makeswift/src/init.ts
We were having issues with Arc browser because we were destroying the HTTP server socket too early. When a request would come in, it would be immediately canceled. The code snippet seemed to indicate that Chrome would hold on to the connection, keeping it open, but after testing it, this didn't seem to be the case. For this reason, I removed the code snippet since it didn't seem to have any beneficial effects at the moment.
=> fix: stop destroy socket too early

.github/ISSUE_TEMPLATE/1-bug-report-makeswift-runtime.yaml, .github/ISSUE_TEMPLATE/2-bug-report-makeswift-cli.yaml, .github/ISSUE_TEMPLATE/3-bug-report-examples-catalyst.yaml
=> chore: add basic issue templates

.changeset/plenty-oranges-act.md, packages/runtime/src/components/builtin/Text/Text.tsx
Bringing `Text` in line with the rest of the builtins.
=> fix(runtime): "function components cannot be given refs" on the builtin `Text` component

.changeset/chilly-peaches-wonder.md, packages/runtime/src/runtimes/react/components/PreviewProvider.tsx, packages/runtime/src/state/react-builder-preview.ts
Decouple `MessageChannel` creation from the middleware creation to make store initalization compatible with React's [strict mode](https://react.dev/reference/react/StrictMode). 
Next.js has React's strict mode [enabled by default](https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode) in dev; when running w/ Next.js 14.2 and [App Router](https://nextjs.org/docs/app) in dev, creation of the channel in the middleware was resulting in a secondary "ghost" store instance that was handling some of the dispatch methods, leading to a de-synchronized runtime state.
=> fix(runtime): pages are not editable when running in dev w/ NextJS 14.2

.changeset/tiny-lies-check.md, packages/runtime/src/next/api-handler/handlers/proxy-preview-mode.ts
Resolve occasional `TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array Buffer` when previewing a site built using Next.js Pages router.
=> fix(runtime): resolve occasional `ERR_INVALID_ARG_TYPE` error in Node.js console output

.github/workflows/canary-release.yml
On a merge to `main`, this job will run.
This job:
- checks out `canary`
- merges `main` into it
- Puts the branch into pre-release mode, if it isn't already
- Versions the packages (`pnpm exec changeset version`)
- Commits the above changes ([example here](https://github.com/makeswift/makeswift/commit/3c2461719e5abdfc03bf3cef6b886d37a628ff4a))
- Runs `pnpm exec changeset publish` (this step is untested)
- Pushes any new commits up to the `canary` branch
To read why I went with a merge-based approach, [see here](https://www.notion.so/makeswift/Merge-Based-Canary-Branching-Workflow-064e3de018234229874a77434e4734d4?pm=c).
=> Configure Github Action for canary releases

.changeset/small-pets-attend.md, packages/runtime/src/next/components/tests/page-prop-controller.tsx, packages/runtime/src/next/components/tests/page-responsive-select-prop-controller.test.tsx, packages/runtime/src/runtimes/react/controls.tsx
Add missing render hook + test. Following up https://github.com/makeswift/makeswift/pull/765.
=> fix: correctly render controls with versioned `ResponsiveSelect` data

.changeset/curly-dragons-train.md, packages/runtime/src/runtimes/react/components/ElementReference.tsx
This bug only happened on component that doesn't use forwardRef.
This happened because we're relying on FindDomNode when the component does not use forwardRef. Unfortunately, for ElementReference, we render the ElementData, instead of Element, which has the FindDomNode fallback.
This commit fix that issue, and we render Element instead of ElementData.
=> fix: global element not selectable after it's blurred

.changeset/odd-experts-punch.md, packages/runtime/src/components/shared/Link/index.tsx
Workaround for https://github.com/vercel/next.js/issues/66650
=> fix: uncaught client exception on incomplete, protocol-only links

.changeset/little-ads-return.md, apps/nextjs-app-router/src/app/[lang]/[[...path]]/page.tsx, apps/nextjs-pages-router/src/pages/[[...path]].tsx, packages/runtime/package.json, packages/runtime/src/next/client.ts, packages/runtime/src/next/tests/client.get-pages.test.ts, packages/runtime/src/next/utils/async-iterable.ts, packages/runtime/src/next/utils/pagination.ts, pnpm-lock.yaml
Updates the sample applications to use the new paginated v4 `getPages` endpoint. Also adds a deprecation notice to `getSitemap`.
=> feat: introduce v4 `getPages` endpoint

examples/basic-typescript-pages/package.json, examples/basic-typescript-pages/pages/[[...path]].tsx, examples/basic-typescript/app/[[...path]]/page.tsx, examples/basic-typescript/package.json, examples/bigcommerce-catalyst/app/(default)/[...path]/page.tsx, examples/bigcommerce-catalyst/package-lock.json, examples/bigcommerce-catalyst/package.json, examples/bigcommerce/package.json, examples/bigcommerce/pages/[[...path]].tsx, examples/shopify/package.json, examples/shopify/pages/[[...path]].tsx, examples/thirdweb/package.json, examples/thirdweb/pages/[[...path]].tsx
Currently using the snapshot version of the runtime to test everything. Will modify this PR when the new version of the runtime is released.
=> chore: update example apps with new `getPages` method

.changeset/cold-weeks-hang.md, packages/runtime/src/next/client.ts
Removes the `publishedAt` sort option from the `getPages` client method, replacing it with `description`.
=> fix: remove `getPages` `publishedAt` sort option

packages/runtime/src/next/components/tests/controls/__snapshots__/checkbox-control.test.tsx.snap, packages/runtime/src/next/components/tests/controls/checkbox-control.test.tsx
Rewrites the checkbox control tests to check exact DOM node contents rather than ternary based text inclusions. Also uses data-driven unit tests to check all boolean values.
=> fix: create stricter checkbox controls tests

packages/controls/package.json, packages/prop-controllers/package.json, packages/runtime/jest.config.ts, packages/runtime/jest.polyfills.js, packages/runtime/jest.resolver.js, packages/runtime/package.json, packages/runtime/src/jest-setup.ts, packages/runtime/src/mocks/server.ts, packages/runtime/src/next/components/tests/controls/__snapshots__/checkbox-control.test.tsx.snap, packages/runtime/src/next/components/tests/controls/__snapshots__/color-control.test.tsx.snap, packages/runtime/src/next/components/tests/controls/checkbox-control.test.tsx, packages/runtime/src/next/components/tests/controls/color-control.test.tsx, packages/runtime/src/next/components/tests/controls/page-control-prop-rendering.tsx, packages/runtime/src/next/tests/client.get-pages.test.ts, packages/runtime/src/utils/tests/element-data-test-test.ts, pnpm-lock.yaml
Adds tests for rendering the color control, while refactoring the existing color control tests to use a shared helper functionality for testing. Also introduces msw for handling swatch retrieval in the color control tests.
=> refactor: create control test helper

.changeset/quick-eagles-sort.md, packages/runtime/src/components/page/Page.tsx, packages/runtime/src/next/components/page.tsx, packages/runtime/src/state/actions.ts, packages/runtime/src/state/modules/read-write-documents.ts, packages/runtime/src/state/react-builder-preview.ts
This is required for "Host-driven navigation". Right now the builder gets the `elementTreeId` from the `pageId` in the builder.
We want to inverse this control and let the host drive the builder.
=> Send an event during initialize() to inform the builder which document/element tree to subscribe to

.changeset/late-wolves-vanish.md, .changeset/tall-coins-compare.md, packages/controls/src/controls/select/__snapshots__/select.test.js.snap, packages/controls/src/controls/select/select.test.js, packages/controls/src/controls/select/select.ts, packages/runtime/CHANGELOG.md, packages/runtime/src/builder/serialization/__snapshots__/control-serialization.test.ts.snap, packages/runtime/src/builder/serialization/control-serialization.test.ts, packages/runtime/src/builder/serialization/control-serialization.ts
Modifies controls deserialization to still continue if an invalid config from the user is provided. This allows for the panels of successfully created controls to still appear in the builder. Addresses the case where some users are not passing valid configs during prop registration, but the issue is not surfaced due to them most likely not using TypeScript.
=> fix: gracefully deserialize controls

.changeset/big-bats-retire.md, packages/controls/src/controls/shape/shape.test.ts, packages/controls/src/controls/shape/shape.ts
`introspect` should never return `undefined`.
=> fix: gracefully handle the mismatch between `Shape` definition vs data when introspecting

.changeset/eight-ears-smile.md, packages/runtime/src/runtimes/react/components/ElementData.tsx, packages/runtime/src/runtimes/react/utils/can-accept-ref.test.tsx, packages/runtime/src/runtimes/react/utils/can-accept-ref.ts
We still always attempt to forward to lazy components since we can't know if they accept refs without loading them.
Partially resolves https://linear.app/makeswift/issue/ENG-1609/solve-forwardref-warnings-coming-from-renderhook-components
=> runtime: forward ref only if the component supports it

.changeset/calm-bobcats-grow.md, packages/runtime/src/runtimes/react/controls.tsx, packages/runtime/src/runtimes/react/legacy-controls.tsx
Prep for [removing `<RenderHook>`](https://github.com/makeswift/makeswift/pull/814), no semantic changes
=> refactor: move legacy descriptor prop rendering into its own file

.changeset/two-days-repair.md, packages/controls/src/index.ts, packages/controls/src/lib/predicates/deepEqual.ts, packages/controls/src/lib/predicates/index.ts, packages/controls/src/lib/predicates/is.ts, packages/controls/src/lib/predicates/shallowEqual.ts, packages/runtime/src/utils/deepEqual.ts, packages/runtime/src/utils/is.ts, packages/runtime/src/utils/shallowEqual.ts
No semantic changes, prep for https://github.com/makeswift/makeswift/pull/814
=> refactor: move `is`, `deepEqual` and `shallowEqual` predicates to `@makeswift/controls`

.changeset/new-cows-flow.md, packages/runtime/src/builder/serialization/control-serialization.test.ts, packages/runtime/src/builder/serialization/control-serialization.ts
Modify the deserializeControls function to accept unknown data, which is checked to be a serialized control at runtime. Also expand the error callback to return the erroring key/serialized data that failed during deserialization.
=> fix: verify serialized controls during deserialization

.changeset/khaki-squids-play.md, packages/controls/jest.config.json, packages/controls/src/controls/shape/__snapshots__/shape.test.ts.snap, packages/controls/src/controls/shape/shape.test.ts, packages/controls/src/controls/shape/shape.ts, packages/controls/src/jest-setup.ts
This doesn't help us to gracefully handle property "swaps" along the lines of an example outlined below, but it is more conceptually correct and stops us from erring on stale/abandoned props. The current behavior I'm replacing is a regression introduced in https://github.com/makeswift/makeswift/pull/781.
"Property swap" example (to be tackled later):
1. Define a custom component taking a `Shape` prop with a key `a` mapped to `Number`
2. Add the component to the page
3. Change prop `a` to be a `List({ type: Number() })`
=> fix: `Shape` iterates through definition instead of data/value keys

apps/nextjs-pages-router/next.config.mjs, packages/runtime/src/next/client.ts, packages/runtime/src/state/modules/__tests__/api-resources.test.ts, packages/runtime/src/state/modules/api-resources.ts
... plus updated tests.
`getAPIResource` and other API resource functions already enforce at compile-time whether we should pass `locale` to access an API resource of a specific type, but actions do not. However, we don't want to place the burden of conditionally passing the locale on action creators, as actions are often dispatched from a context that handles all resource types. Instead, we make it okay to pass a locale in all resource action payloads and have the reducer use the locale for scoping only if we are operating on a localized resource.
=> fix(runtime): don't use locale to partition non-localized resources

.changeset/fuzzy-planes-peel.md, packages/runtime/src/next/api-handler/index.ts
=> fix(runtime): not found localized global components saved as `null`

.changeset/wicked-kiwis-begin.md, apps/nextjs-app-router/.eslintrc.json, apps/nextjs-app-router/package.json, apps/nextjs-app-router/src/app/[lang]/[[...path]]/page.tsx, apps/nextjs-app-router/src/app/layout.tsx, apps/nextjs-app-router/tsconfig.json, apps/nextjs-pages-router/.eslintrc.json, apps/nextjs-pages-router/package.json, apps/nextjs-pages-router/src/pages/_document.tsx, apps/nextjs-pages-router/tsconfig.json, packages/runtime/package.json, packages/runtime/src/next/api-handler/handlers/proxy-draft-mode.ts, packages/runtime/src/next/api-handler/index.ts, packages/runtime/src/next/client.ts, packages/runtime/src/next/draft-mode/draft-mode-script.tsx, packages/runtime/src/next/draft-mode/index.tsx, packages/runtime/src/next/index.tsx, packages/runtime/src/runtimes/react/find-dom-node.tsx, packages/runtime/src/runtimes/react/lib/react-dom.ts, pnpm-lock.yaml
Next.js 15 / React 19 RC support
The Makeswift custom `Document` export has been moved from `@makeswift/runtime/next` to `@makeswift/runtime/next/document`. To migrate, adjust the custom `Document` import in `src/pages/_document.ts` as follows:
```diff
- export { Document as default } from '@makeswift/runtime/next'
+ export { Document as default } from '@makeswift/runtime/next/document'
```
=> feat(runtime): Next.js 15 / React 19 RC support

packages/runtime/src/next/components/MakeswiftComponent.tsx, packages/runtime/src/runtimes/react/hooks/use-register-document.ts, packages/runtime/src/state/actions.ts
Currently, the runtime only sends builder documents during the initialization
of the builder <-> host connection. This means that any functionality that could
rely on a remount of a document after the connection has already been
established will not work, since the registration will not be communicated to
the builder.
This change addresses this by adding a document registration hook for embedded
components that sends a builder registration action on mount.
https://github.com/user-attachments/assets/d0c7a560-b3a0-4f94-92ae-f4a02fda36bc
=> refactor: continuous builder document registration

packages/controls/src/serialization/function-serialization.test.ts, packages/controls/src/serialization/function-serialization.ts
See the added test for a reproduce:
=> fix(controls): fix stalled calls/memory leaks on repeated function deserialization

packages/runtime/src/runtimes/react/components/Element.tsx
Use a separate `FindDomNode` for rendering the fallback which won't be overruled by the element callback ref.
Before:
https://github.com/user-attachments/assets/39c61206-7868-4e1f-a519-73b7882f34cc
After:
https://github.com/user-attachments/assets/298ea89d-16bb-4da4-b9b9-9ff90e6656b7
=> fix(runtime): use separate finddomnode for fallbacks

packages/runtime/src/next/client.ts, packages/runtime/src/next/components/MakeswiftComponent.tsx, packages/runtime/src/next/components/tests/makeswift-component-rendering.test.tsx, packages/runtime/src/runtimes/react/components/Document.tsx, packages/runtime/src/runtimes/react/components/DocumentRoot.tsx, packages/runtime/src/runtimes/react/components/Element.tsx, packages/runtime/src/state/modules/read-only-documents.ts
Remove support for passing a fallback to the `MakeswiftComponent` component.
=> refactor(runtime): remove fallback prop

packages/runtime/src/next/client.ts, packages/runtime/src/runtimes/react/components/Document.tsx, packages/runtime/src/state/actions.ts, packages/runtime/src/state/modules/read-only-documents.ts, packages/runtime/src/state/modules/read-write-documents.ts, packages/runtime/src/state/react-page.ts, packages/runtime/src/state/utils/get-root-element-from-document.test.ts, packages/runtime/src/state/utils/get-root-element-from-document.ts
Rather than passing metadata about whether the root element exists or not, we now allow the root element to be null, and also pass an initial root element field. This allows us to derive whether the root exists, as well as use this initial root to reset the data later.
=> refactor(runtime): pass initial root element directly

.changeset/warm-avocados-bathe.md, packages/runtime/src/next/api-handler/handlers/manifest.ts, packages/runtime/src/next/api-handler/handlers/webhook/index.ts, packages/runtime/src/next/api-handler/handlers/webhook/site-published.ts, packages/runtime/src/next/api-handler/handlers/webhook/types.ts, packages/runtime/src/next/api-handler/index.ts, packages/runtime/src/next/client.ts, packages/runtime/src/state/makeswift-api-client.ts
This adds revalidation support for <MakeswiftComponent /> on App Router
=> feat: add site.published webhook handler for global revalidation

packages/runtime/src/next/client.ts
For now we're looking to mirror the behavior of getPageSnapshot, see: https://makeswifthq.slack.com/archives/C080BNSNEG7/p1733744344493169
=> Require site version for fetching component snapshot

apps/nextjs-app-router/src/makeswift/provider.tsx, packages/runtime/src/next/components/tests/controls/page-control-prop-rendering.tsx, packages/runtime/src/next/components/tests/global-element-rendering.test.tsx, packages/runtime/src/next/components/tests/makeswift-component-rendering.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-backgrounds-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-border-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-date-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-element-id-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-font-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-gap-y-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-grid-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-image-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-images-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-link-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-margin-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-navigation-links-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-padding-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-prop-controller.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-social-links-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-table-form-fields-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-table-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-text-area-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-text-input-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-text-style-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-video-prop-controller.test.tsx, packages/runtime/src/next/components/tests/prop-controllers/page-width-prop-controller.test.tsx, packages/runtime/src/runtimes/react/components/RuntimeProvider.tsx
As long as passing `previewMode` is required for making the site editable in the builder, there is no good reason for defaulting it. See [this thread](https://makeswifthq.slack.com/archives/C057U8TLT9U/p1736182157072199?thread_ts=1735925807.739969&cid=C057U8TLT9U) for context.
=> fix(runtime): require passing `previewMode` to the runtime provider

.changeset/tall-queens-smile.md, packages/runtime/src/next/draft-mode/draft-mode-script.tsx, packages/runtime/src/next/preview-mode.tsx
**Steps to reproduce the issue:**
- Open a page in the builder
- Open the console on the dev tools
- Select the host console instead of `top`, 
- Send a fetch request with a custom header. 
**Before the fix, the custom header is overwritten:**
---
**After the fix, the custom header is preserved:**
=> fix: patched fetch in the builder to preserve existing request headers

.changeset/young-shoes-cheer.md, packages/runtime/src/next/client.ts, packages/runtime/src/next/components/MakeswiftComponent.tsx, packages/runtime/src/next/components/tests/makeswift-component-rendering.test.tsx, packages/runtime/src/next/tests/client.get-component-snapshot.test.ts, packages/runtime/src/state/actions.ts, packages/runtime/src/state/modules/read-only-documents.ts
companion PR: https://github.com/makeswift/cosmos/pull/765 
eng-7353 (part of eng-7271)
=> Update document payload to support 'detach' UX for editing localized element trees that inherit from a parent locale

.github/workflows/preview-deployment-playwright-tests.yml
Since Jan 9th our tests have been failing. This was caused by Github Actions now pointing to Ubuntu 24 for `ubuntu-latest`. This PR switches it back to `ubuntu-22.04` since it will be supported for the next two years
=> fix(actions): Use ubuntu-22.04

.changeset/good-falcons-yawn.md, apps/nextjs-app-router/src/app/api/makeswift/[...makeswift]/route.ts, packages/runtime/src/next/api-handler/index.ts, packages/runtime/src/next/client.ts, packages/runtime/src/next/tests/client.get-component-snapshot.test.ts, packages/runtime/src/next/tests/client.get-pages.test.ts, packages/runtime/src/runtimes/react/__tests__/react-runtime.test.tsx, packages/runtime/src/runtimes/react/components/PreviewProvider.tsx, packages/runtime/src/runtimes/react/hooks/use-dispatch.ts, packages/runtime/src/runtimes/react/hooks/use-react-runtime.tsx, packages/runtime/src/runtimes/react/hooks/use-store.ts, packages/runtime/src/runtimes/react/react-runtime.ts, packages/runtime/src/runtimes/react/runtime-core.ts
Removing a potential source of hard-to-trace issues stemming from users forgetting to pass the runtime instance to the classes in subj.
=> refactor: require passing `runtime` to `Makeswift` client/`MakeswiftApiHandler`

packages/controls/src/controls/group/group.ts, packages/controls/src/controls/shape/v2/index.ts, packages/controls/src/controls/shape/v2/shape-v2-control.ts, packages/runtime/src/core/index.ts
Required for backward compatibility with the pre-release runtime snapshots.
=> fix: expose `ShapeV2Control.CHILD_CONTROL_MESSAGE` constant for the builder

.changeset/famous-clocks-relate.md, packages/runtime/package.json
Also remove React's `19.0.0-rc` peer deps now that React 19 is officially out.
=> fix: update `@types/react` peer deps to 19.0.0

.changeset/great-crabs-prove.md, packages/runtime/src/runtimes/react/hooks/use-resolved-props.ts
Updates prop resolution to fallback to the default value for a prop (if available) on failure.
https://github.com/user-attachments/assets/279012a5-067d-4fd7-8ea6-4e950280a28e
=> fix: prevent corrupted data from stopping rendering

.github/workflows/snapshot-release.yml
Don't run snapshot release action on "Version and publish packages" PRs, skip publishing if there are warnings.
See [this thread](https://makeswifthq.slack.com/archives/C014SCS4G75/p1734489089618689) for more context.
=> fix: don't run snapshot release action on release PRs

.changeset/new-pandas-heal.md, packages/runtime/src/runtimes/react/controls/control.tsx, packages/runtime/src/runtimes/react/hooks/use-resolved-props.ts, packages/runtime/src/runtimes/react/hooks/use-resolved-value.ts, packages/runtime/src/runtimes/react/utils/prop-error-handling-proxy.ts
Also switches to using `console.warn` for data parsing failures instead of `console.error`.
=> fix: fallback to default during individual prop resolution

.changeset/healthy-baboons-switch.md, packages/runtime/src/runtimes/react/controls/rich-text-v2/ReadOnlyTextV2.tsx, packages/runtime/src/runtimes/react/controls/rich-text/ReadOnlyText.tsx
This was [previously fixed in 0.23.0 canary builds](https://github.com/makeswift/makeswift/pull/868), but lost during the merge from `main`.
=> fix:  "attempted import" errors on registering components in server-side code

.changeset/honest-swans-bake.md, packages/runtime/src/next/api-handler/handlers/proxy-draft-mode.test.ts, packages/runtime/src/next/api-handler/handlers/proxy-draft-mode.ts
We should be using forwarded headers for host and protocol since it is a better source of truth of where the request is coming coming from.
This also fixes an issue with running runtime in a docker container.
=> feat(runtime): Use headers to create proxied url

.changeset/nervous-badgers-lay.md, packages/runtime/src/runtimes/react/components/ElementData.tsx
The message on the placeholder component we show to the user when we can't find a registered component doesn't reveal any component details (see below), which is probably appropriate, but we should log the details to the console to aid the troubleshooting.
=> chore: log missing components' types

packages/runtime/src/core/index.ts
We moved breakpoint types & algorithms to the `@makeswift/controls` package as a part of the unified controls interface refactoring/[element tree rendering rewrite](https://github.com/makeswift/makeswift/commit/11ae3c27d9663acb82ea3ea7e961da04af23e739). These, however, are also used in the builder, and a while ago we decided that the builder shouldn't directly import from `@makeswift/controls`. Re-exporting them in under `@makeswift/runtime/core` entrypoint here.
=> chore: re-expose breakpoint types & algorithms for the builder

.github/workflows/preview-deployment-playwright-tests.yml
upload-artifact@v3 was deprecated on 1/30/25. See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/.
=> fix(workflows): update upload-artifact to v4

.changeset/sweet-days-return.md, packages/runtime/src/components/page/Page.tsx, packages/runtime/src/components/page/PageHead.tsx, packages/runtime/src/components/page/page-seo-settings.ts, packages/runtime/src/next/components/page.tsx, packages/runtime/src/next/components/tests/__snapshots__/makeswift-page-metadata-rendering.test.tsx.snap, packages/runtime/src/next/components/tests/makeswift-page-metadata-rendering.test.tsx
Introduce prop to the Page component that will selectively render metadata in the page `head` with data from Makeswift, or pass booleans to blanket enable/disable this data.
=> feat: selectively render head tags in Page

.changeset/curvy-forks-give.md, packages/runtime/src/next/client.ts, packages/runtime/src/next/tests/client.get-component-snapshot.test.ts
Fixes "lost" edits to slots/embedded components with slashes in their IDs (a likely scenario for dynamic pages).
https://github.com/user-attachments/assets/34247fc1-c36a-42ce-95e4-7bef4dbf42a0
https://github.com/user-attachments/assets/494f9a3c-e252-49cb-8de6-af3c93b8baa3
=> fix: encode component ID when fetching its element tree

.changeset/famous-dingos-talk.md, packages/runtime/src/components/shared/Link/index.tsx, packages/runtime/src/next/hooks/use-is-pages-router.ts
Passing `locale={false}` to `NextLink` in the App Router context is silently ignored in Next 13/14, but [generates a console error in Next 15](https://github.com/vercel/next.js/discussions/74703).
=> fix: don't pass `locale` prop to `NextLink` when running under App Router

.changeset/good-turtles-compare.md, packages/runtime/src/components/builtin/Carousel/Carousel.tsx
Fix missing padding, arrow hover styles on `Carousel` when running under the App Router. Note that this has been broken since we introduced support for the App Router. See inline comments below for details.
=> fix: missing `Carousel` styles

.changeset/kind-garlics-tease.md, packages/runtime/src/next/api-handler/handlers/proxy-draft-mode.test.ts, packages/runtime/src/next/api-handler/handlers/proxy-draft-mode.ts
Rename the [recently introduced `FORCE_HTTP` env variable](https://github.com/makeswift/makeswift/releases/tag/%40makeswift%2Fruntime%400.23.2) to better reflect its scope. 
See [this thread](https://makeswifthq.slack.com/archives/C014SCS4G75/p1738608865174819) for more context.
=> fix: `FORCE_HTTP` -> `MAKESWIFT_DRAFT_MODE_PROXY_FORCE_HTTP`

.changeset/odd-crabs-prove.md, packages/runtime/src/runtimes/react/hooks/use-cache-data.ts
Fixes an issue where element prop resolution occurs before the cache hydration action from the parent is kicked off from an effect. By prioritizing parent dispatches ahead of children effects, we ensure that the children are reading from hydrated state.
=> fix: prioritize cache hydration over prop resolution

.changeset/new-sheep-matter.md, packages/runtime/src/next/client.ts
When we read from the API resource reducer, we're using the locale from `useDocumentLocale`, which is coming from `snapshot.document.locale`. We have a legacy behavior in our API server where if the `locale === defaultLocale`, the server will return the locale as `null`.
When we write to the API resource reducer, we're using the `cacheData` from the introspect function, which gets the locale from `getPageSnapshot` argument directly, without checking if it's the defaultLocale or not.
When we pass the default locale to `getPageSnapshot`:
```
const snapshot = getPageSnapshot({ locale: 'en-US' })
```
The snapshot:
```
{ document: { locale: null } }
```
The cacheData:
```
{ "id": "...", "value": { ... }, "locale": "en-US" }
```
This commit fixes the issue by using the locale returned from the …
=> fix: cache key mismatch when default locale is passed to getPageSnapshot

.changeset/cool-rats-enjoy.md, packages/runtime/src/state/modules/__tests__/__snapshots__/element-trees.test.ts.snap, packages/runtime/src/state/modules/__tests__/element-trees.test.ts, packages/runtime/src/state/modules/__tests__/fixtures/element-trees-demo-component.tsx, packages/runtime/src/state/modules/__tests__/fixtures/element-trees.ts, packages/runtime/src/state/modules/element-trees.ts
Do not show an error message for reset ops with an empty path. Also correctly handle element deletion on resets.
=> fix(runtime): correctly handle reset element ops

.changeset/tidy-dragons-sing.md, packages/runtime/src/api/react.ts, packages/runtime/src/api/site-version.ts, packages/runtime/src/next/api-handler/handlers/proxy-draft-mode.ts, packages/runtime/src/next/api-handler/handlers/proxy-preview-mode.ts, packages/runtime/src/next/api-handler/index.ts, packages/runtime/src/next/client.ts, packages/runtime/src/next/draft-mode/index.tsx, packages/runtime/src/next/preview-mode.tsx, packages/runtime/src/next/tests/client.get-component-snapshot.test.ts, packages/runtime/src/runtimes/react/components/RuntimeProvider.tsx, packages/runtime/src/runtimes/react/host-api-client.tsx, packages/runtime/src/state/makeswift-api-client.ts
Refactor the API Handler to no longer rely on API requests being proxied. Instead, the host client is configured to retrieve certain versions of resources based on an explicit version passed to it.
=> refactor(runtime): decouple api handler endpoints from Next.js draft mode

.changeset/kind-dryers-beam.md, packages/runtime/package.json, packages/runtime/src/next/api-handler/handlers/draft-mode.ts, packages/runtime/src/next/api-handler/handlers/preview-mode.ts, packages/runtime/src/next/api-handler/index.ts, packages/runtime/src/next/middleware/exceptions.ts, packages/runtime/src/next/middleware/index.ts, packages/runtime/src/next/middleware/request-utils.test.ts, packages/runtime/src/next/middleware/request-utils.ts, pnpm-lock.yaml
Adds utility functions for getting draft/preview data and bypass tokens and constructing a proxy response. Will be used for bringing proxying capabilities to hosts that are currently patching requests with a bypass token in middleware, which does not work for SSGd pages.
=> feat: introduce draft proxy utility functions

apps/nextjs-app-router/src/app/[lang]/not-found.tsx
Introduces a `not-found` so that the 404 page is properly rendered.
Before:
After:
=> fix: kitchen sink app router 404 page

.changeset/hot-shoes-cheat.md, packages/runtime/src/runtimes/react/hooks/use-resolved-value.ts
Regression was found when the builtin Link component (present on the builtin button, image, etc.) would not update links whenever prop data changed. This is because the builtin Link uses the `useResolvedValue` hook, which only triggers prop resolution on mount. Fixes the issue by triggering resolution whenever the resolvable constructed inside changes. Sister fix to: https://github.com/makeswift/makeswift/pull/955
Demos (in both demos, pay attention to the browser link preview in the bottom left):
Before
https://github.com/user-attachments/assets/0dc564b6-c977-44bb-89dd-59e92a743a01
After:
https://github.com/user-attachments/assets/c62dea5e-772a-4a24-be02-698950d3d7ec
=> fix: trigger resolution when resolvable in `useResolvedValue` changes

.github/dependabot.yml
Aligning yaml config to what is closer to dependabot config as it is a bit confusing. NPM is apparently used even if pnpm is what is used by the service
=> chore: syntax change for dependabot.yml

.changeset/calm-apples-smell.md, packages/runtime/src/runtimes/react/components/Document.tsx, packages/runtime/src/runtimes/react/hooks/use-document-context.ts, packages/runtime/src/runtimes/react/hooks/use-resource-resolver.ts
As part of the document context, we were passing the document root element. This means that every edit would result in the context value changing, resulting in all children rerendering. For larger element trees, this means that all props in the document would be re-resolved for any prop change. This fix only passes the necessary fields for the document (key and locale).
Before:
https://github.com/user-attachments/assets/8504cd9e-d4be-489f-98b8-6fdad4e9a450
After:
https://github.com/user-attachments/assets/aeba54cb-2725-4975-9e49-0fdca7db4847
All measurements were taken on the same element tree by modifying the same prop.
Before regression, runtime `v0.22.3`  (7.2ms per render):
Regression (71.8ms per render, order of magnitude higher than before):
With Fix (5.2ms per render)
=> fix: avoid document context rerenders

.changeset/flat-nails-mate.md, packages/runtime/src/runtimes/react/hooks/use-register-document.ts
(just showing that hot reload dropzones are still working)
https://github.com/user-attachments/assets/3e198f5e-7d39-4ad1-b357-e6334163089b
=> Change server dispatch for document registration

.changeset/happy-pandas-give.md, packages/runtime/src/runtimes/react/components/hooks/use-builder-connection-ping.ts
Pass the app origin as the `targetOrigin` for all `postMessage` calls for explicitness.
=> chore: pass app origin as named param in connection hooks

.changeset/lemon-ravens-divide.md, packages/runtime/src/next/api-handler/handlers/manifest.ts, packages/runtime/src/next/client.ts, packages/runtime/src/next/tests/__snapshots__/client.get-page-snapshot.test.ts.snap, packages/runtime/src/next/tests/client.get-page-snapshot.test.ts
Last piece of [ENG-7803](https://linear.app/makeswift/issue/ENG-7803/make-localized-pages-online-by-default).
=> feat: localized pages are online by default, fallback to the base locale

.changeset/shy-actors-grow.md, packages/runtime/src/components/builtin/Root/Root.tsx, packages/runtime/src/next/root-style-registry.tsx
[Tailwind v4 use @layer](https://tailwindcss.com/blog/tailwindcss-v4#designed-for-the-modern-web). This caused the CSS reset to override the Tailwind styles.
[source](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)
Add `enableCssReset` option to `RootStyleRegistry` to disable the CSS reset.
https://github.com/user-attachments/assets/73bb766e-600f-4c14-b124-76fefd686081
=> feat: add `enableCssReset` option to `RootStyleRegistry` to support Tailwind v4 and other `@layer`-based CSS framework

.changeset/beige-emus-knock.md, packages/makeswift-next-plugin/index.js, packages/runtime/src/next/api-handler/handlers/redirect-preview.ts
Fixes a regression introduced in 0.24.0 when we removed [this code](https://github.com/makeswift/makeswift/blob/a645d1e83bc0fb4422ff14387738b3aa93c91c60/packages/runtime/src/next/api-handler/handlers/proxy-preview-mode.ts#L92).
https://github.com/user-attachments/assets/da1dfb57-8bd6-4648-b3fb-144e771eeca8
=> fix(pages router): localized pages redirect to the base locale in the builder

.changeset/cold-cars-check.md, .changeset/hip-deer-rescue.md, packages/runtime/CHANGELOG.md, packages/runtime/src/components/shared/BackgroundsContainer/components/BackgroundVideo/index.tsx
This PR fixes the issue when a video content from a Makeswift page does not play or plays in a full-screen mode on iOS.
https://github.com/user-attachments/assets/e08f58b0-1731-4040-b24c-b98caf8ff17f
https://github.com/user-attachments/assets/bde4f436-169e-4c74-ab97-a758c99fbd21
https://github.com/user-attachments/assets/398a3985-e06d-48a9-9a9e-0615e449d5db
https://github.com/user-attachments/assets/701d7ada-953b-4bef-93e4-6c2e760ca6e3
=> hotfix/runtime 0.23.14

.changeset/strange-colts-arrive.md, packages/runtime/src/next/api-handler/handlers/redirect-draft.test.ts, packages/runtime/src/next/api-handler/handlers/redirect-draft.ts
Add support for comma-separated list of values in the `x-forwarded-proto` header.
=> fix: `Invalid URL` error on attempt to open a reverse-proxied site in the builder

.changeset/large-dryers-sleep.md, packages/runtime/src/next/components/tests/__snapshots__/makeswift-page-metadata-rendering.test.tsx.snap, packages/runtime/src/next/components/tests/makeswift-page-metadata-rendering.test.tsx, packages/runtime/src/runtimes/react/components/draft-switcher/draft-switcher.tsx
Fix `Cannot render a sync or defer <script> outside of the main document` console error in the App Router sites.
Verified for both App and Pages Router.
=> fix: `<script>` tag error in the console when a site is loaded in the builder

.changeset/fair-crabs-deny.md, packages/runtime/src/components/shared/ErrorBoundary.tsx, packages/runtime/src/runtimes/react/components/Element.tsx
Prevent rendering errors from breaking entire pages by surrounding each element component with an error boundary. This allows the user to delete any erroring elements.
Before:
https://github.com/user-attachments/assets/1401174b-436e-4001-a401-034ac87d345c
After:
https://github.com/user-attachments/assets/2ce0af18-a508-47c8-8ccd-4e6a689a397c
=> fix: surround elements with error boundaries

.changeset/stupid-seas-deny.md, packages/controls/src/controls/typography/__fixtures__/index.ts, packages/controls/src/controls/typography/__fixtures__/typography-without-id.ts, packages/controls/src/controls/typography/__snapshots__/copy.test.ts.snap, packages/controls/src/controls/typography/copy.test.ts, packages/controls/src/controls/typography/typography.ts
After demo: https://linear.app/makeswift/issue/ENG-8876/consistent-error-on-getting-typographies-in-catalyst#comment-29d82f07
=> Fix copying typography data - allow undefined id in output

.changeset/few-hornets-wink.md, packages/controls/src/controls/rich-text/v1/__snapshots__/copy.test.ts.snap, packages/controls/src/controls/rich-text/v2/__snapshots__/rich-text.test.ts.snap, packages/controls/src/controls/rich-text/v2/rich-text.test.ts, packages/controls/src/controls/typography/typography.test.ts, packages/controls/src/controls/typography/typography.ts
The current behavior for clearing typography data from the copy context is to not return any data altogether. However, since the typography data permits for an undefined ID, we should follow the rule of smallest granularity to only clear the typography ID, rather than the entire data.
https://github.com/user-attachments/assets/c6e5abc6-c371-458f-999e-47dec52508c1
=> fix: only clear typography id when marked for removal

.changeset/wise-wombats-sing.md, packages/runtime/src/components/page/PageHead.tsx, packages/runtime/src/next/components/tests/__snapshots__/makeswift-page-metadata-rendering.test.tsx.snap
Reintroduces the Open Graph / Twitter Card  meta tags for the `<Page />` component's title.
=> fix: meta tags for Open Graph / Twitter title

packages/runtime/.prettierignore, packages/runtime/package.json, packages/runtime/src/builder/serialization/controls/types.ts, packages/runtime/src/builder/unstructured-introspection/unstructured-introspection.test.ts, packages/runtime/src/client/index.ts, packages/runtime/src/components/builtin/SocialLinks/options.tsx, packages/runtime/src/components/hooks/useRouterLocaleSync.ts, packages/runtime/src/components/shared/BackgroundsContainer/components/Backgrounds/index.tsx, packages/runtime/src/next/api-handler/handlers/redirect-draft.test.ts, packages/runtime/src/next/api-handler/handlers/redirect-draft.ts, packages/runtime/src/next/api-handler/handlers/redirect-preview.ts, packages/runtime/src/next/api-handler/handlers/webhook/index.ts, packages/runtime/src/next/client.ts, packages/runtime/src/next/components/tests/makeswift-page-metadata-rendering.test.tsx, packages/runtime/src/next/index.tsx, packages/runtime/src/next/tests/server.makeswift-api-handler.test.ts, packages/runtime/src/next/tests/test-utils.ts, packages/runtime/src/runtimes/react/components/PageProvider.tsx, packages/runtime/src/runtimes/react/components/draft-switcher/draft-switcher.tsx, packages/runtime/src/runtimes/react/element-imperative-handle.ts, packages/runtime/src/runtimes/react/hooks/use-register-document.ts, packages/runtime/src/state/modules/builder-edit-mode.ts, packages/runtime/src/state/modules/components-meta.ts, packages/runtime/src/utils/intersection.ts, packages/runtime/src/utils/pagination.ts
Note that we have multiple different Prettier configurations across the `controls` and `runtime` packages, as well as at the root of the repository, and unifying them is outside the scope of this PR. This change simply brings the `runtime` package in line with its own Prettier configuration.
=> chore(runtime): fix Prettier formatting issues, no semantic changes

.changeset/stale-lemons-wonder.md, packages/runtime/src/next/index.tsx, packages/runtime/src/next/root-style-registry.tsx, packages/runtime/src/next/testing/react-provider.tsx, packages/runtime/src/runtimes/react/root-style-registry.tsx
Decouple core `RootStyleRegistry` implementation from Next.js. No additional tests as we already have extensive test coverage for this.
=> feat: framework-independent `RootStyleRegistry` implementation

packages/runtime/src/components/builtin/Slot/Slot.tsx, packages/runtime/src/next/components/tests/controls/page-control-prop-rendering.tsx, packages/runtime/src/next/components/tests/makeswift-component-rendering.test.tsx, packages/runtime/src/next/index.tsx, packages/runtime/src/runtimes/react/components/MakeswiftComponent.tsx, packages/runtime/src/runtimes/react/components/Slot.tsx, packages/runtime/src/runtimes/react/components/SlotProvider.tsx
They weren't really coupled to Next.js in the first place, so mostly just moving them under `runtimes/react`. No user-visible changes.
=> chore: decouple `Slot`/`MakeswiftComponent` from Next.js

packages/runtime/src/next/components/tests/__fixtures__/element-data/image-component.ts, packages/runtime/src/next/components/tests/__fixtures__/resources/files.ts, packages/runtime/src/next/components/tests/__fixtures__/resources/index.ts, packages/runtime/src/next/components/tests/__fixtures__/resources/swatches.ts, packages/runtime/src/next/components/tests/components/__snapshots__/image-component-rendering.test.tsx.snap, packages/runtime/src/next/components/tests/components/image-component-rendering.test.tsx, packages/runtime/src/next/testing/page-rendering.tsx
Basic rendering test for the built-in `Image` component. No semantic changes. Prep for `next/image` decoupling.
See also https://github.com/makeswift/makeswift/pull/1078.
=> tests: built-in `Image` component rendering tests

packages/runtime/src/next/components/tests/__fixtures__/element-data/box-component.ts, packages/runtime/src/next/components/tests/components/__snapshots__/box-component-rendering.test.tsx.snap, packages/runtime/src/next/components/tests/components/box-component-rendering.test.tsx
Basic rendering test for the built-in `Box` w/ a background image. No semantic changes. Prep for `next/image` decoupling.
See also https://github.com/makeswift/makeswift/pull/1077.
=> tests: built-in `Box` component w/ background image rendering tests

packages/runtime/package.json, packages/runtime/src/slate/BlockPlugin/__tests__/clearBlockKeyForDevice.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/dedent.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/indent.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/normalization.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/setBlockKeyForDevice.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/toggleList.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/unwrapInline.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/unwrapList.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/utils/getSelectedListItems.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/wrapInline.test.tsx, packages/runtime/src/slate/BlockPlugin/__tests__/wrapList.test.tsx, packages/runtime/src/slate/InlineModePlugin/__tests__/inlineMode.test.tsx, packages/runtime/src/slate/InlinePlugin/__tests__/getValue.test.tsx, packages/runtime/src/slate/InlinePlugin/__tests__/onChange.test.tsx, packages/runtime/src/slate/LinkPlugin/__tests__/getValue.test.tsx, packages/runtime/src/slate/LinkPlugin/__tests__/onChange.test.tsx, packages/runtime/src/slate/TextAlignPlugin/__tests__/getValue.test.tsx, packages/runtime/src/slate/TypographyPlugin/__tests__/clearActiveTypographyStyle.test.tsx, packages/runtime/src/slate/TypographyPlugin/__tests__/clearDeviceActiveTypography.test.tsx, packages/runtime/src/slate/TypographyPlugin/__tests__/detachActiveTypography.test.tsx, packages/runtime/src/slate/TypographyPlugin/__tests__/normalization.test.tsx, packages/runtime/src/slate/TypographyPlugin/__tests__/setActiveTypographyId.test.tsx, packages/runtime/src/slate/TypographyPlugin/__tests__/setActiveTypographyStyle.test.tsx, packages/runtime/src/slate/test-helpers/editor-v1.tsx, packages/runtime/src/slate/test-helpers/editor-v2-inline.tsx, packages/runtime/src/slate/test-helpers/editor-v2.tsx, pnpm-lock.yaml
Upgrading to get the improved type inlining / [declaration tracking for dependencies](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html). No usage of any newer TS features is being introduced, so this should be a no-op from the user’s standpoint.
Prep for https://github.com/makeswift/makeswift/pull/1090.
=> chore: upgrade to the latest TypeScript (5.1.6 -> 5.9.2)

.changeset/curvy-teachers-rhyme.md, packages/runtime/src/api/react.ts, packages/runtime/src/next/components/framework-provider/index.tsx, packages/runtime/src/runtimes/react/components/RuntimeProvider.tsx, packages/runtime/src/runtimes/react/components/framework-context.tsx, packages/runtime/src/runtimes/react/host-api-client.tsx, packages/runtime/src/state/makeswift-api-client.ts
Decouple host API client's resource fetching from Next.js-specific request tagging.
=> feat: framework-independent host API client

packages/runtime/src/components/builtin/Root/Root.tsx
=> chore: decouple built-in `Root` component (missed import from `../next`)

packages/runtime/package.json, packages/runtime/src/components/builtin/Video/Video.tsx, packages/runtime/src/components/shared/BackgroundsContainer/components/BackgroundVideo/index.tsx, packages/runtime/src/components/shared/react-player.ts, packages/runtime/src/utils/esm-compat.ts, pnpm-lock.yaml
Prep for the Remix implementation. Resolves `TypeError: __vite_ssr_import_3__.ReactPlayer.canPlay is not a function at BackgroundVideo` etc.
=> chore: `react-player` Vite SSR/ESM compatibility

.changeset/dirty-shoes-juggle.md, packages/makeswift-next-plugin/index.js, packages/runtime/src/api-handler/handlers/redirect-live.ts, packages/runtime/src/next/tests/server.api-handler-redirect-live.test.ts, packages/runtime/src/runtimes/react/components/preview-switcher/preview-toolbar.tsx
Updates the query param to exit preview mode to omit the "x-" prefix convention.
=> chore: update exit preview query param name

packages/runtime/src/next/root-style-registry.tsx, packages/runtime/src/runtimes/react/root-style-registry.tsx
Code outside of the `runtimes/react` dir should not have knowledge / depend on the fact that we're using Emotion.
=> refactor: encapsulate Emotion style tag creation

packages/express-react/package.json
While `changeset` does support `alpha` releases, the workflow is complicated and they don't recommend creating prereleases from `main`: https://changesets-docs.vercel.app/en/prereleases
=> chore: change `express-react` version from `0.0.0-alpha` to `0.0.1`

.changeset/young-ravens-greet.md, packages/runtime/src/next/api-handler/config/app-router.ts
Fixes a regression in ba2e9de where the API handler does not match vanilla Requests. In older versions of Next (prior to 15.5.0), the inbound request is a Request. In newer versions, the request is a NextRequest. To maintain compatibility with all Next.js versions, we match against both.
=> fix: match Request and NextRequest in API handler

.changeset/polite-dancers-teach.md, .changeset/twenty-tips-ring.md, packages/controls/src/controls/definition.ts, packages/controls/src/controls/group/group.test.types.ts, packages/controls/src/controls/group/group.ts, packages/controls/src/controls/list/list.test.types.ts, packages/controls/src/controls/list/list.ts, packages/controls/src/controls/shape/v1/shape.test.types.ts, packages/controls/src/controls/shape/v1/shape.ts, packages/controls/src/controls/slot/slot.ts, packages/controls/src/controls/text-area/text-area.ts, packages/controls/src/controls/text-input/text-input.ts, packages/runtime/src/controls/__tests__/fixtures/list.ts, packages/runtime/src/controls/__tests__/translation.test.ts, packages/runtime/src/controls/rich-text-v2/rich-text-v2.ts, packages/runtime/src/state/__tests__/fixtures/translations.ts, packages/runtime/src/state/__tests__/react-page.test.tsx
Fix a regression introduced in v0.20.0 of the runtime, where we no longer check for null data when merging translated data.
=> fix: check null data at translation merge

.changeset/pink-fishes-raise.md, packages/hono-react/src/server/api-handler.ts, packages/hono-react/src/server/env.ts, packages/hono-react/src/server/preview.ts
Adjust middleware to not require an API key on middleware creation.
=> fix: extract API key from context

.changeset/famous-ladybugs-eat.md, packages/runtime/package.json
Per https://publint.dev/rules#exports_types_should_be_first, "types" should be declared first.
=> fix: type export declaration order

.changeset/brown-crabs-visit.md, .changeset/fuzzy-ways-destroy.md, packages/runtime/package.json
Fixes errors shown by [Publint](https://publint.dev/@makeswift/runtime@0.0.0-snapshot-20250925223243):
- `module` should come before `require`: https://publint.dev/@makeswift/runtime@0.0.0-snapshot-20250925223243
- Incorrect file paths exposed for the client export
=> Runtime package.json corrections

.github/workflows/nextjs-bundle-analysis.yml
Fix a configuration error in the workflow for bundle analysis that results in bundle analysis still running on PRs for example apps.
=> fix: skip bundle analysis on example apps

.changeset/famous-bees-unite.md, packages/makeswift-next-plugin/index.d.ts, packages/makeswift-next-plugin/index.js
Add a warning message that appears during the build/start or dev process if the user has explicitly disabled the `previewMode`.
=> feat: add warning when `previewMode` is disabled

.changeset/nice-guests-kiss.md, packages/runtime/src/builder/breakpoints/index.ts, packages/runtime/src/builder/index.ts
Export some previously removed types that are used by the builder. These types are exposed via the internal `builder` entry point.
=> fix: export necessary internal types for builder
